name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v5
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: 'yarn'
      - name: Install dependencies
        run: |
          yarn install
      - name: Run Prettier
        run: |
          yarn format:check
      - name: Run ESLint
        run: |
          yarn lint:check
